### ISSUE TITLE
Not able to authenticate with secret

### ISSUE THREAD

**Issue by terraform-class** [devopsgoat/terraform-aws-transfer#12]
The test from the AWS Transer Service comes back with a 200

{
    "Response": "{}",
    "StatusCode": 200,
    "Message": "",
    "Url": "https://t8xxxxxxxx.execute-api.us-east-1.amazonaws.com/prod/servers/s-8ea8963df3c3xxxxxxx/users/tester01/config"
}

ERRORS AUTH_FAILURE Method=publickey User=tester01 Message="The user is unrecognized" SourceIP=
 

```resource "aws_secretsmanager_secret" "secret01" {
  name                = "SFTP/tester01"
}


resource "aws_secretsmanager_secret_version" "secret01" {
  secret_id     = aws_secretsmanager_secret.secret01.id
  secret_string = <<EOF
{
  "HomeDirectoryDetails": "[{\"Entry\": \"/\", \"Target\": \"/REMOVEDBUCKETNAME/$${Transfer:UserName}\"}]",
  "Password": "tester2020",
  "Role": "arn:aws:iam::REMOVEDACCOUNTNUMBER:role/transfer-user-iam-role",
  "UserId": "tester01"
}
EOF
}
```

Errors from Lambda

```

020-12-11T11:36:48.669-06:00[ERROR] PermissionError: [Errno 13] Permission denied: '/var/task/index.py'Traceback (most recent call last):  File "/var/lang/lib/python3.7/imp.py", line 300, in find_module    with open(file_path, 'rb') as file: | [ERROR]  PermissionError: [Errno 13] Permission denied:  '/var/task/index.py' Traceback (most recent call last):   File  "/var/lang/lib/python3.7/imp.py", line 300, in find_module     with  open(file_path, 'rb') as file:
-- | --
 



```

020-12-11T11:36:48.669-06:00[ERROR] PermissionError: [Errno 13] Permission denied: '/var/task/index.py'Traceback (most recent call last):  File "/var/lang/lib/python3.7/imp.py", line 300, in find_module    with open(file_path, 'rb') as file: | [ERROR]  PermissionError: [Errno 13] Permission denied:  '/var/task/index.py' Traceback (most recent call last):   File  "/var/lang/lib/python3.7/imp.py", line 300, in find_module     with  open(file_path, 'rb') as file:
-- | --

**Comment by terraform-class** [comment]
It turned out to be the index.py file had to be chmod to 644
