### ISSUE TITLE
Lambda is not able to parse json

### ISSUE THREAD

**Issue by Sumitit81** [devopsgoat/terraform-aws-transfer#23]
Hi,

I am trying to implement this code. However the code is breaking at below point: -

![image](https://user-images.githubusercontent.com/71323099/149616890-254333e7-269f-4c86-a2a4-5d406d81c554.png)

When I try to print the resp, I get below output: -

{'ARN': 'arn:aws:secretsmanager:us-east-1:XXXXX:secret:SFTP/paligo-user-rVOe1O', 'Name': 'SFTP/paligo-user', 'VersionId': 'F46E9FCA-F0FE-46CF-B872-ECB474F5DF1D', 'SecretString': '{\r\n  "HomeDirectoryDetails": "[{\\"Entry\\": \\"/\\", \\"Target\\": \\"/test.devopsgoat/${Transfer:UserName}\\"}]",\r\n  "Password": "abc",\r\n  "Role": "arn:aws:iam::XXXXX:role/transfer-user-iam-role-dev",\r\n  "UserId": "paligo-user",\r\n  "AcceptedIpNetwork": "192.168.1.0/24",\r\n}\r\n', 'VersionStages': ['AWSCURRENT'], 'CreatedDate': datetime.datetime(2022, 1, 15, 6, 49, 35, 952000, tzinfo=tzlocal()), 'ResponseMetadata': {'RequestId': 'f0de005e-5f84-4e3c-8705-e53ec608cc97', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Sat, 15 Jan 2022 09:12:38 GMT', 'content-type': 'application/x-amz-json-1.1', 'content-length': '569', 'connection': 'keep-alive', 'x-amzn-requestid': 'f0de005e-5f84-4e3c-8705-e53ec608cc97'}, 'RetryAttempts': 0}}

further when the code tries to return json.loads(resp["SecretString"]) below error is observed.

[ERROR] JSONDecodeError: Expecting property name enclosed in double quotes: line 7 column 1 (char 273)
Traceback (most recent call last):
  File "/var/task/index.py", line 55, in lambda_handler
    secret_dict = get_secret(input_username)
  File "/var/task/index.py", line 208, in get_secret_sm
    return json.loads(resp["SecretString"])
  File "/var/lang/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/var/lang/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/var/lang/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)

Could you please help me resolve this issue

Thanks

**Comment by darren-reddick** [comment]
There is a formatting error in the HomeDirectoryDetails value within the json string. Just trying to work out which part it is....

**Comment by nilsbillo** [comment]
@darren-reddick ANy progress on this ?

**Comment by redleader36** [comment]
I believe this is just the trailing comma at the end of your example on examples/public-secrets/README.md.  If you use this following terraform code (just removing the comma), the error is resolved:
```
resource "aws_secretsmanager_secret" "secret" {
  name                = "SFTP/user1"
}

resource "aws_secretsmanager_secret_version" "secret" {
  secret_id     = "${aws_secretsmanager_secret.secret.id}"
  secret_string = <<-EOF
    {
      "HomeDirectoryDetails": "[{\"Entry\": \"/\", \"Target\": \"/test.devopsgoat/$${Transfer:UserName}\"}]",
      "Password": "Password1",
      "Role": "arn:aws:iam::XXXXXXX:role/transfer-user-iam-role",
      "UserId": "user1",
      "AcceptedIpNetwork": "192.168.1.0/24"
    }
  EOF
}
```
